### ISSUE TITLE
ArrayIndexOutOfBoundsException with polyline no-go

### ISSUE THREAD

**Issue by nrenner** [abrensch/brouter#159]
I get a RouteServer exeption when passing a polyline:

http://brouter.de/brouter-web/#map=15/48.8735/2.2936/standard&lonlats=2.300177,48.872139;2.29022,48.875188&polylines=2.29713,48.876683,2.292323,48.870022,99

```
java.lang.ArrayIndexOutOfBoundsException: -10043
	at btools.util.CheapRuler.getLonLatToMeterScales(CheapRuler.java:57)
	at btools.router.OsmNogoPolygon.calcBoundingCircle(OsmNogoPolygon.java:94)
	at btools.server.request.ServerHandler.parseNogoPolygons(ServerHandler.java:293)
	at btools.server.request.ServerHandler.readNogoPolygons(ServerHandler.java:259)
	at btools.server.request.ServerHandler.readRoutingContext(ServerHandler.java:64)
	at btools.server.RouteServer.run(RouteServer.java:184)
```

Locally with openjdk 11.0.3 I get this message:  
`java.lang.ArrayIndexOutOfBoundsException: Index -10043 out of bounds for length 1800`

**Comment by Phyks** [comment]
This was an error of logic in the code. Fixed in https://github.com/abrensch/brouter/pull/165.
