### ISSUE TITLE
Running the BRouter HTTP server 

### ISSUE THREAD

**Issue by JW148** [abrensch/brouter#394]
Hi, I am really interested in using BRouter as the routing engine for a project I'm working on and would like some help setting up the server. Thanks in advance for any replies.

**Comment by polyscias** [comment]
It is pretty easy to run BRouter on a PC, if you have java running.

On Linux I start Brouter using:

`/usr/bin/java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp brouter.jar btools.server.RouteServer segments4 profiles2 customprofiles 17777 3 127.0.0.1`

See also [server.cmd](https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.cmd) (Windows) or [server.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.sh) (Linux)

In the directory where you start you should have:

1. A brouter.jar file
2. A profiles2 directory with the profiles you want to use.
3. A segments4 directory with the [segments](http://brouter.de/brouter/segments4/) you want to use

1 + 2 you can get using a zip file from http://brouter.de/brouter/revisions.html

127.0.0.1 is the address brouter is listening on, 17777 is the port and 3 is the maximum number of instances.


When you starts successfully brouter you should see something like:

`BRouter 1.6.3 / 20122021`

Next you can get one or more routes using for example curl:

`curl -o route.gpx "http://127.0.0.1:17778/brouter?lonlats=4.5,51.85|4.55,51.95&profile=trekking&alternativeidx=0&format=gpx"`

**Comment by EssBee59** [comment]
Could you give a short description of your project?
The answer above is perfect if you intend to work on Windows or Linux, but if you intend to work under Android, you should better use the Brouter-app.

**Comment by JW148** [comment]
> It is pretty easy to run BRouter on a PC, if you have java running.
> 
> On Linux I start Brouter using:
> 
> `/usr/bin/java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp brouter.jar btools.server.RouteServer segments4 profiles2 customprofiles 17777 3 127.0.0.1`
> 
> See also [server.cmd](https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.cmd) (Windows) or [server.sh](https://github.com/abrensch/brouter/blob/master/misc/scripts/standalone/server.sh) (Linux)
> 
> In the directory where you start you should have:
> 
> 1. A brouter.jar file
> 2. A profiles2 directory with the profiles you want to use.
> 3. A segments4 directory with the [segments](http://brouter.de/brouter/segments4/) you want to use
> 
> 1 + 2 you can get using a zip file from http://brouter.de/brouter/revisions.html
> 
> 127.0.0.1 is the address brouter is listening on, 17777 is the port and 3 is the maximum number of instances.
> 
> When you starts successfully brouter you should see something like:
> 
> `BRouter 1.6.3 / 20122021`
> 
> Next you can get one or more routes using for example curl:
> 
> `curl -o route.gpx "http://127.0.0.1:17778/brouter?lonlats=4.5,51.85|4.55,51.95&profile=trekking&alternativeidx=0&format=gpx"`

Thanks so much! Works perfectly for what I need.

**Comment by JW148** [comment]
@polyscias is it possible to run the Brouter server using a public IP address? I get a _java.net.BindException_ when using a public IP.

**Comment by polyscias** [comment]
> I get a java.net.BindException when using a public IP.

That is not something caused by the brouter code.

Maybe [the port/address is already in use](https://stackoverflow.com/questions/12737293/how-do-i-resolve-the-java-net-bindexception-address-already-in-use-jvm-bind).

The other possibility is that you do not having the permissions to use that port/address, for that see [java.net.BindException: Permission denied](https://stackoverflow.com/questions/25544849/java-net-bindexception-permission-denied-when-creating-a-serversocket-on-mac-os)

**Comment by JW148** [comment]
Thanks for the quick reply, @polyscias. Having gone through the suggestions made in the posts you linked, I am still unable to get the Brouter server running using a public IP address (the _java.net.BindException_ is still the issue). Are there any other possibilities why I can't get it to run?

**Comment by polyscias** [comment]
Are you running under Linux or Windows?

Is there any more information following the java.net.BindException?

**Comment by JW148** [comment]
This is what I get running it on Ubuntu (in windows subsystem for linux):

`~/brouter-1.6.3 $ /usr/bin/java -Xmx128M -Xms128M -Xmn8M -DmaxRunningTime=300 -cp brouter.jar btools.server.RouteServer segments4 profiles2 customprofiles 3000 3 ***.***.***.***                                       BRouter 1.6.3 / 20122021                                                                                                Exception in thread "main" java.net.BindException: Cannot assign requested address (Bind failed)                                at java.base/java.net.PlainSocketImpl.socketBind(Native Method)                                                         at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)                                    at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)                                                          at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)                                                        at btools.server.RouteServer.main(RouteServer.java:353)`

**Comment by polyscias** [comment]
I assume things work when you replace ***.***.***.*** by 127.0.0.1, right?

It could have something to do with your /etc/hosts, see [Cannot assign requested address using ServerSocket.socketBind](https://stackoverflow.com/questions/8965155/cannot-assign-requested-address-using-serversocket-socketbind)

Can you also check what "sudo lsof -i:3000" is returning?

**Comment by JW148** [comment]
Yes, the server runs fine when using 127.0.0.1.

I've tried the suggestions form the post you linked about the /etc/hosts but to no avail.

sudo lsof -i:3000 did not return anything (I have also tried running the server on various different ports).

**Comment by EssBee59** [comment]
Hello JW148,

Under windows the bindadress is not necessary, also under linux it seems optional:
Did you tried without a bindadress as last parameter?

**Comment by polyscias** [comment]
I think it is time to try if you can run another server on the address/port you want, so try running a netcat server on the ***.***.***.*** address and port 3000:

`nc -l ***.***.***.*** 3000`

Does that work? If not, what error does it return?

**Comment by JW148** [comment]
@polyscias I've ended up using AWS to host the server - works perfectly for what I need. Thanks for your help.

**Comment by polyscias** [comment]
Okay, that is good to hear!

Would be good to close the Issue then.
