### ISSUE TITLE
Crash on update

### ISSUE THREAD

**Issue by Fabian42** [abrensch/brouter#574]
When I click "Update 1117 tiles", the app crashes:

```
java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
	at androidx.work.Data.toByteArrayInternal(Data.java:407)
	at androidx.work.Data$Builder.build(Data.java:957)
	at btools.routingapp.BInstallerActivity.downloadAll(BInstallerActivity.java:215)
	at btools.routingapp.BInstallerActivity.downloadInstalledTiles(BInstallerActivity.java:487)
	at btools.routingapp.BInstallerActivity.lambda$onCreate$0$btools-routingapp-BInstallerActivity(BInstallerActivity.java:126)
	at btools.routingapp.BInstallerActivity$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27896)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7400)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

When I manually select all the tiles, I get the same result, except lines 5 and 6 are:
```
	at btools.routingapp.BInstallerActivity.downloadSelectedTiles(BInstallerActivity.java:478)
	at btools.routingapp.BInstallerActivity.lambda$onCreate$0$btools-routingapp-BInstallerActivity(BInstallerActivity.java:123)
```

This is probably related to the amount of tiles I have downloaded, but it didn't happen before.

**Comment by afischerdev** [comment]
It belongs to the androidx.work.Data class.
We should protect this calls not to get a crash.
